Added active state for the side navigation
remix-run/react-router-website pull request #127
Opened 2024-10-30 02:58 UTC by sardorml

Added active state for the side navigation heading based on user scroll, as mentioned in #62.

2024-10-30 03:05 UTC, sardorml commented
https://github.com/user-attachments/assets/3ddd2aa1-84f0-4a02-9331-4d9bd5874d95

@brookslybrand  this is how it looks. Please let me know If i need to make any changes to the code!

2024-10-31 16:12 UTC, brookslybrand requested changes
Thanks so much @sardorml for taking this on!

It works pretty well, I have a number of nits on the code.

2024-10-31 16:12 UTC, brookslybrand commented on app/components/on-this-page.tsx
> +  });
No reason to re-run this `useEffect` every time the state changes. Let me know if there's a bug this is addressing

```suggestion
  }, []);
```

2024-10-31 16:12 UTC, brookslybrand commented on app/components/on-this-page.tsx
> +        if (window.scrollY > h.offsetTop - 100) {
Where does the 100 come from? Is that just a random padding to make this work?

2024-10-31 16:12 UTC, brookslybrand commented on app/components/on-this-page.tsx
> +              }
Small nit, but add this import

```ts
import classNames from "classnames";
```

and we can update to the following

```suggestion
              className={classNames(
                activeHeading == heading.slug &&
                  "text-gray-900 dark:text-gray-50",
                "block py-1 text-sm text-gray-400 hover:text-gray-900 active:text-red-brand dark:text-gray-400 dark:hover:text-gray-50  dark:active:text-red-brand"
              )}
```

2024-10-31 16:12 UTC, brookslybrand commented on app/components/on-this-page.tsx
> +    const container = document.getElementsByClassName("md-prose");
Let's avoid using a classname for this look up

In the parent components we set a ref on the container, I would just pass that down. Something like

```tsx
export function LargeOnThisPage({
  mdRef,
  doc,
}: {
  mdRef: React.RefObject<HTMLDivElement>;
  doc: Doc;
}) {
  const [activeHeading, setActiveHeading] = useState("");

  useEffect(() => {
    const node = mdRef.current;
    if (!node) return;
    // all the logic
  }, [mdRef]);
  
  // all the jsx
  
}
```

2024-10-31 18:10 UTC, sardorml commented on app/components/on-this-page.tsx
> +    const container = document.getElementsByClassName("md-prose");
Got it. I will change it to use ref of the container.

2024-10-31 18:12 UTC, sardorml commented on app/components/on-this-page.tsx
> +    const headings = container[0].querySelectorAll("h2");
Will add h3 as well. Thanks for the example.

2024-10-31 18:16 UTC, sardorml commented on app/components/on-this-page.tsx
> +        if (window.scrollY > h.offsetTop - 100) {
Yes, it was a random padding added to account for the navigation header, ensuring the link state becomes active when scrolling reaches below the navigation. I see that the h-16 Tailwind class is being used to set the height, which is 64px. I’ll change it to 64. Does that work?

2024-10-31 18:35 UTC, brookslybrand commented on app/components/on-this-page.tsx
> +        if (window.scrollY > h.offsetTop - 100) {
Yeah that's fine, just leave a comment where you got the number

2024-11-01 06:50 UTC, sardorml commented on app/components/on-this-page.tsx
> +        if (window.scrollY > h.offsetTop - 100) {
https://github.com/user-attachments/assets/dbaad1cf-d46f-4cc8-a917-dab5d840266f

It might be better to set it to 100 or higher, as selecting a section in the side navigation activates the section above if the h2 and h3 headings don’t reach the bottom of the header due to extra padding.

2024-11-01 07:04 UTC, sardorml commented on app/components/on-this-page.tsx
> +    const headings = container[0].querySelectorAll("h2");
Done

2024-11-01 07:04 UTC, sardorml commented on app/components/on-this-page.tsx
> +              }
Done

2024-11-01 07:05 UTC, sardorml commented on app/components/on-this-page.tsx
> +    const container = document.getElementsByClassName("md-prose");
Changed

2024-11-01 14:45 UTC, brookslybrand commented on app/components/docs-header/docs-header.tsx
> +    // 26:on-this-page.tsx Added 64px to scrollY to set the active heading state when h reach bottom of the Header. Number 64 comes from class h-16 (4rem,64px)
```suggestion
    // Added 64px to scrollY to offset the height of the header (h-16)
```

2024-11-01 15:30 UTC, brookslybrand approved these changes
Hey @sardorml this is really great, thank you again for doing this, I'm going to go ahead and ship it! Really excited for people to have this feature :)

If you're interested, feel free to add this to [the remix website](https://github.com/remix-run/remix-website) as well (no pressure though)

Please let me know if you have any questions about the changes I made

2024-11-01 15:30 UTC, brookslybrand commented on app/components/doc-layout.tsx
> +            key={doc.slug}
When you switched pages before the highlighting wouldn't work

2024-11-01 15:30 UTC, brookslybrand commented on app/components/on-this-page.tsx
> +        // 100px arbitrary value to to offset the height of the header (h-16)
I actually liked 100 more, it means that the highlight shows up before the heading goes behind the top nav banner. Also, I put the comment here since that's where we use this value

2024-11-01 15:30 UTC, brookslybrand commented on app/components/on-this-page.tsx
> +      }
This could be improved further, but it's fine for now. I wanted to make sure that we're not updating the state and causing re-renders when this nav is not block (i.e. on smaller screen sizes)

2024-11-01 15:30 UTC, brookslybrand commented on app/components/on-this-page.tsx
> +        }
Flipping the array and searching backwards until we find the first matching heading breaking out of the loop is a bit faster. Either way the code was pretty fast, but since this runs a lot (ever scroll), I figured it's worth improving the algorithm a little

The averages before while scrolling were ~.25ms per function invocation, now they're down to ~.13ms, so ~50% improvement

2024-11-01 15:30 UTC, merged

2024-11-02 03:30 UTC, sardorml commented on app/components/on-this-page.tsx
> +        }
This is awesome @brookslybrand! I'm curious—what tool did you use to benchmark the function invocation? I'd love to know how I can measure function performance myself in the future.

2024-11-02 03:37 UTC, sardorml commented
Hey @brookslybrand,

Thanks for the detailed code review and all the helpful comments! I left a note asking about ways to benchmark function performance for future reference, but otherwise, I have no questions.

And yes, I’d be happy to add this to the Remix website—I’ll submit a PR today.

Thanks again for the great feedback!